name:                json
version:             0.1.0.0
github:              "githubuser/json"
license:             BSD3
author:              "Sasha Dufourt"
maintainer:          "example@example.com"
copyright:           "2021 Sasha Dufourt"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/json#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 0.7
- HUnit >= 1.6 && < 1.7

library:
  source-dirs: src

tests:
  json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json
